name: Notify Main Repo

on:
  push:
    branches:
      - master  # React ì˜ master ë¸Œëœì¹˜ê°€ í‘¸ì‹œë  ë•Œ ì‹¤í–‰

jobs:
  notify-main:
    runs-on: ubuntu-latest

    steps:
      - name: Send Webhook to Main Repo
        run: |
          curl -X POST -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.PAT_TOKEN }}" \
          -d '{"event_type": "update_submodule", "client_payload": {"submodule": "React"}}' \
          https://api.github.com/repos/Nea4321/YCS_Certificate/dispatches

      - name: Send Discord Notification
        run: |
          curl -H "Content-Type: application/json" \
          -X POST \
          -d '{
            "username": "ì¶˜ì‹ì´R",
            "content": "**ğŸ“¢ ì£¼ì¸ë‹˜, `React` ì„œë¸Œëª¨ë“ˆì´ ì—…ë°ì´íŠ¸ë˜ì—ˆì–´ìš”!!**"
          }' \
          "${{ secrets.REACT_WEBHOOK_URL }}"
